app_key: "84f5fhg0xinj03f"
app_secret: <%= ENV["DROPBOX_APP_SECRET"] %>
access_token: "ay02x6kwnzbr836m"
access_token_secret: <%= ENV["DROPBOX_TOKEN_SECRET"] %>
user_id: "21411555"
access_type: "app_folder"